#!/usr/bin/env python

import time

class Asciipicture():
    def __init__(self, asciiname):
        self.asciiname = asciiname

    def asciitruppe(self):
        print("               _____")
        print("              /     \ ")
        print("              vvvvvvv  /|__/|")
        print("                 I   /O,O   |")
        print("                 I /_____   |      /|/|")
        print("                J|/^ ^ ^ \  |    /00  |    _//|")
        print("                 |^ ^ ^ ^ |W|   |/^^\ |   /oo |")
        print("                  \m___m__|_|    \m_m_|   \mm_|")
        print("")

    def asciiskull(self):
        print("  _____")
        print(" /     \ ")
        print("| () () |")
        print(" \  ^  /")
        print("  |||||")
        print("  |||||")
        print("")

    def asciitruppeded(self):
        print("               _____")
        print("              /     \ ")
        print("              vvvvvvv  /|__/|")
        print("                 I   /X,X   |")
        print("                 I /_____   |      /|/|")
        print("                J|/^ ^ ^ \  |    /xx  |    _//|")
        print("                 |^ ^ ^ ^ |W|   |/^^\ |   /xx |")
        print("                  \m___m__|_|    \m_m_|   \mm_|")
        print("")

    def asciigametitelback(self):
        print(" ______ ______  __  __  ______  ______  __  __  ______ ______  __  __  ______  ______  ______    ")
        print("/\  ___/\  == \/\ \/\ \/\  ___\/\  ___\/\ \_\ \/\__  _/\  ___\/\ \/ / /\  __ \/\  == \/\  == \   ")
        print("\ \  __\ \  __<\ \ \_\ \ \  __\\\ \ \___\ \  __ \/_/\ \\\ \  __\\\ \  _\"-\ \ \/\ \ \  __<\ \  __<   ")
        print(" \ \_\  \ \_\ \_\ \_____\ \_____\ \_____\ \_\ \_\ \ \_\\\ \_____\ \_\ \_\ \_____\ \_\ \_\ \_____\ ")
        print("  \/_/   \/_/ /_/\/_____/\/_____/\/_____/\/_/\/_/  \/_/ \/_____/\/_/\/_/\/_____/\/_/ /_/\/_____/ ")
        print("")

    def asciigametitel(self):
        print("\033[38;5;204m  ______ ______  __  __  ______  ______  __  __  ______ ______  __  __  ______  ______  ______    \033[0m")
        print("\033[38;5;204m /\  ___/\  == \/\ \/\ \/\  ___\/\  ___\/\ \_\ \/\__  _/\  ___\/\ \/ / /\  __ \/\  == \/\  == \   \033[0m")
        print("\033[38;5;204m \ \  __\ \  __<\ \ \_\ \ \  __\\\ \ \___\ \  __ \/_/\ \\\ \  __\\\ \  _\"-\ \ \/\ \ \  __<\ \  __<   \033[0m")
        print("\033[38;5;204m  \ \_\  \ \_\ \_\ \_____\ \_____\ \_____\ \_\ \_\ \ \_\\\ \_____\ \_\ \_\ \_____\ \_\ \_\ \_____\ \033[0m")
        print("\033[38;5;204m   \/_/   \/_/ /_/\/_____/\/_____/\/_____/\/_/\/_/  \/_/ \/_____/\/_/\/_/\/_____/\/_/ /_/\/_____/ \033[0m")
        print("\033[38;5;131m                                                                                         M RATED\033[0m")

    def asciimuchskullded(self):
        print(" .-~~-.     .-~~-.     .-~~-.")
        print("(_^..^_)   (_^..^_)   (_^..^_)")
        print("  ||||       ||||       ||||")
        print("             `--'       ||||")
        print("  ||||                  `--'")
        print("  `--'")
        print(" .-~~-.     .-~~-.     .-~~-.")
        print("(_^..^_)   (_^..^_)   (_`..'_)")
        print("  ||||       HHHH       ||||")
        print("  ||||       `--'")
        print(" .-~~-.     .-~~-.     .-~~-.")
        print("(_p..q_)   (_~,,~_)   (_O..O_)")
        print("  ||||       ||||       |[]|")
        print("                        `--'")


    def asciiskullded(self):
        print("  _____")
        print(" /     \ ")
        print("|  X X  |")
        print(" \  ^  /")
        print("  |||||")
        print("  |||||")

    def asciienteryourname(self):
        print("   ____     __                                 _  __              ")
        print("  / __/__  / /____ ____  __ _____  __ ______  / |/ /__ ___ _  ___ ")
        print(" / _// _ \/ __/ -_) __/ / // / _ \/ // / __/ /    / _ `/  ' \/ -_)")
        print("/___/_//_/\__/\__/_/    \_, /\___/\_,_/_/   /_/|_/\_,_/_/_/_/\__/ ")
        print("                       /___/                                      ")
        print("")

    def asciikommunist(self):
        print("-------------------------")
        print("░░░░░░░░░░░░░░░███████ ]▄▄▄▄▄▄▄▄")
        print("░░░░░░░░░░▂▄▅█████████▅▄▃▂  ")
        print("░░░░░░░░░░I████████████████████].")
        print("░░░░░░░░░░  ◥⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙◤..      ")
        print("")

    def asciifruitsback(self):
        print(" ,(.   (           ,(.   (            ,(.   (           ,(.   (              ,(.   (")
        print("(   ) / \         (   ) / \          (   ) / \         (   ) / \            (   ) / \ ")
        print(" `\"' (   )         `\"' (   )          `\"' (   )         `\"' (   )            `\"' (   )")
        print("      `\"'     ,:.     `  \"'     ,:.        `\"'     ,:.     `  \"'     ,:.          `\"'     ,:.")
        print(" ,           (:::) ,           (:::)  ,           (:::) ,           (:::)    ,           (:::)")
        print(" \`.__.       `-'  \`.__.       `-'   \`.__.       `-'  \`.__.       `-'     \`.__.       `-'")
        print("  `._,'             `._,'              `._,'             `._,'                `._,'")
        print("")

    def asciifruits(self):
        print("\033[38;5;68m  ,(. \033[0m \033[38;5;119m (    \033[0m \033[38;5;68m      ,(. \033[0m \033[38;5;119m (    \033[0m  \033[38;5;68m      ,(. \033[0m \033[38;5;119m (  \033[0m    \033[38;5;68m     ,(. \033[0m \033[38;5;119m ( \033[0m      \033[38;5;68m       ,(. \033[0m \033[38;5;119m (\033[0m")
        print("\033[38;5;68m (   ) \033[0m\033[38;5;119m/ \   \033[0m \033[38;5;68m     (   )\033[0m \033[38;5;119m/ \    \033[0m \033[38;5;68m     (   ) \033[0m\033[38;5;119m/ \  \033[0m   \033[38;5;68m    (   ) \033[0m\033[38;5;119m/ \  \033[0m    \033[38;5;68m      (   )\033[0m \033[38;5;119m/ \ \033[0m")
        print("\033[38;5;202m  `\"' \033[0m\033[38;5;119m(   ) \033[0m  \033[38;5;202m      `\"'\033[0m \033[38;5;119m(   )  \033[0m   \033[38;5;202m     `\"'\033[0m \033[38;5;119m(   )\033[0m  \033[38;5;202m       `\"'\033[0m \033[38;5;119m(   )  \033[0m  \033[38;5;202m        `\"'\033[0m \033[38;5;119m(   )\033[0m")
        print("\033[38;5;130m       `\"'\033[0m    \033[38;5;119m ,:. \033[0m \033[38;5;130m     `\"' \033[0m \033[38;5;119m   ,:. \033[0m \033[38;5;130m      `\"'\033[0m  \033[38;5;119m   ,:. \033[0m \033[38;5;130m     `\"' \033[0m   \033[38;5;119m ,:.  \033[0m \033[38;5;130m       `\"' \033[0m  \033[38;5;119m  ,:.\033[0m")
        print("\033[38;5;130m  ,  \033[0m\033[38;5;204m         (:::)\033[0m\033[38;5;130m , \033[0m\033[38;5;204m          (:::) \033[0m\033[38;5;130m , \033[0m\033[38;5;204m          (:::)\033[0m\033[38;5;130m , \033[0m\033[38;5;204m          (:::)\033[0m\033[38;5;130m    , \033[0m\033[38;5;204m          (:::)\033[0m")
        print("\033[38;5;226m  \`.__. \033[0m\033[38;5;204m      `-' \033[0m\033[38;5;226m \`.__. \033[0m\033[38;5;204m      `-' \033[0m\033[38;5;226m  \`.__. \033[0m\033[38;5;204m      `-'  \033[0m\033[38;5;226m\`.__.  \033[0m\033[38;5;204m     `-'  \033[0m\033[38;5;226m   \`.__.  \033[0m\033[38;5;204m     `-'\033[0m")
        print("\033[38;5;226m   `._,'             `._,'              `._,'             `._,'                `._,'\033[0m")
        print("")

    def asciiaffe(self):
        print("~~~~~~~~~~[]~~    ")
        print("           \      ")
        print("      _ _ //      ")
        print("[]\__( ^ )/       ")
        print("  \_  °3°|        ")
        print("     ) . )/-\    ")
        print("    /  _i_/^\D   ")
        print("   ( /            ")
        print("    \|            ")
        print("     V            ")
        time.sleep(2)
        print("(AFFE)")

    def asciielephant(self):
        print("                              ")
        print("   (())              (())     ")
        print(" ((    ) __________ (    ))   ")
        print("((      (          )      ))  ")
        print("||     (            )     ||  ")
        print("((    (  o\      /o  )    ))  ")
        print(" ((   (   |      |   )    ))  ")
        print("  (    (  |      |  )    )    ")
        print("   (    )  |    |  (    )     ")
        print("    (   )\  |  |  /(   )      ")
        print("     (v)  \_|  |_/  (v)       ")
        print("            |  |              ")
        print("            |  |              ")
        print("            |  |              ")
        print("            (  )              ")
        print("           ([][])             ")
        time.sleep(2)
        print("(ELEPHANT)")

    def asciisnake(self):
        print("  []             _____            ")
        print(" [||]           / v v \    ")
        print("  []            \  ---<         ")
        print("  .=.            \.../       ")
        print("  .=.      ==    ,=,                ")
        print("   .=.   ====== ,=,                  ")
        print("     .=.=========                    ")
        print("---------------------------       ")
        time.sleep(2)
        print("(SNAKE)") 

    def asciigameover(self):
        print("\033[38;5;204m   ___   _              __     ___         __  __  \033[0m")
        print("\033[38;5;204m  / _ \ /_\    /\/\    /__\   /___\/\   /\/__\/__\ \033[0m")
        print("\033[38;5;204m / /_\///_\\\  /    \  /_\    //  //\ \ / /_\ / \// \033[0m")
        print("\033[38;5;204m/ /_\\\/  _  \/ /\/\ \//__   / \_//  \ V //__/ _  \ \033[0m")
        print("\033[38;5;204m\____/\_/ \_/\/    \/\__/   \___/    \_/\__/\/ \_/ \033[0m")
        print("")

    def asciicredits(self):
        print("\033[38;5;204m ____                    __      __             \033[0m")
        print("\033[38;5;204m/\  _`\                 /\ \  __/\ \__          \033[0m")
        time.sleep(1)
        print("\033[38;5;204m\ \ \/\_\  _ __    __   \_\ \/\_\ \ ,_\   ____ \033[0m")
        print("\033[38;5;204m \ \ \/_/_/\`'__\/'__`\ /'_` \/\ \ \ \/  /',__\ \033[0m")
        time.sleep(1)
        print("\033[38;5;204m  \ \ \L\ \ \ \//\  __//\ \L\ \ \ \ \ \_/\__, `\ \033[0m")
        print("\033[38;5;204m   \ \____/\ \_\\  \____\ \___,_\ \_\ \__\/\____/\033[0m")
        time.sleep(1)
        print("\033[38;5;204m    \/___/  \/_/ \/____/\/__,_ /\/_/\/__/\/___/ \033[0m")
        time.sleep(1)
        print("\n   CHEFENTWICKLER: JOHANNA KOCH")
        time.sleep(1)
        print("\n   CHEFDESIGNER: JOHANNA KOCH")
        time.sleep(1)
        print("\n   CHEFIDEE: JOHANNA KOCH")
        time.sleep(1)
        print("\n   AUSSERDEM")
        time.sleep(1)
        print("\n   GRAFIKDESIGNER GRÄUEL AFFE: WYNAND LAUWRENS")
        time.sleep(1)
        print("\n   SPEZIELLEN DANK FÜR DIE UNTERSTÜTZUNG AN:")
        time.sleep(1)
        print("\n   SVEN ZIÖRIEN")
        time.sleep(1)
        print("\n   RAMSIDAMSI")
        time.sleep(1)
        print("\n   KEAY")
        time.sleep(1)
        print("\n   UND DER REST VON TEAM W")
        time.sleep(1)
        print("   \AUSSER FLO")
        time.sleep(1)
        print("\n   AUSSERDEM HERZLICHES BEILEID FÜR ALLE TESTER:")
        time.sleep(1)
        print("\n   DIVERSE COACHES")
        time.sleep(1)
        print("\n   TEAM W")
        time.sleep(1)
        print("\n   LAURA")
        time.sleep(1)
        print("\n   UND ANDERE")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        print("\033[38;5;204m     ______  _____   _    _  ______   _____  _    _  _______  ______   _____   ____   _____   _____  \033[0m")
        print("\033[38;5;204m    |  ____||  __ \ | |  | ||  ____| / ____|| |  | ||__   __||  ____| / ____| / __ \ |  __ \ |  __ \ \033[0m")
        time.sleep(1)
        print("\033[38;5;204m    | |__   | |__) || |  | || |__   | |     | |__| |   | |   | |__   | |     | |  | || |__) || |__) |\033[0m")
        print("\033[38;5;204m    |  __|  |  _  / | |  | ||  __|  | |     |  __  |   | |   |  __|  | |     | |  | ||  _  / |  ___/ \033[0m")
        time.sleep(1)
        print("\033[38;5;204m    | |     | | \ \ | |__| || |____ | |____ | |  | |   | |   | |____ | |____ | |__| || | \ \ | |   _ \033[0m")
        print("\033[38;5;204m    |_|     |_|  \_\ \____/ |______| \_____||_|  |_|   |_|   |______| \_____| \____/ |_|  \_\|_|  (_)\033[0m")
        time.sleep(1)
        print("\n    (DANKE RAMSI)")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\n")
        time.sleep(1)
        print("\nSpecial Tester: DiniMuetter")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")


























